[2024-09-24T11:29:19.500704+02:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/error-handler/DebugClassLoader.php:331)"} []
[2024-09-24T11:32:32.806606+02:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/error-handler/DebugClassLoader.php:331)"} []
[2024-09-24T11:32:32.815064+02:00] request.INFO: Matched route "app_page". {"route":"app_page","route_parameters":{"_route":"app_page","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://127.0.0.1:8080/page","method":"GET"} []
[2024-09-24T11:32:32.816570+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T11:32:32.816685+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:32:32.816790+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:32:32.857478+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:32:32.860309+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:32:32.861920+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:32:32.863402+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:32:32.864137+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:40:16.829313+02:00] request.INFO: Matched route "inicio". {"route":"inicio","route_parameters":{"_route":"inicio","_controller":"App\\Controller\\PageController::inicio"},"request_uri":"http://127.0.0.1:8080/","method":"GET"} []
[2024-09-24T11:40:16.830473+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T11:40:16.830586+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:40:16.830753+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:40:16.839626+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:40:16.844012+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:40:16.844946+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:40:16.845318+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:40:16.846033+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:43:44.915265+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "Class "\ContactoController" does not exist in /home/alumno/PhpstormProjects/symfony-contactos/config/routes/../../src/Controller/ (which is being imported from "/home/alumno/PhpstormProjects/symfony-contactos/config/routes/annotations.yaml"). Make sure there is a loader supporting the "annotation" type." at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/config/Loader/FileLoader.php line 172 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): Class \"\\ContactoController\" does not exist in /home/alumno/PhpstormProjects/symfony-contactos/config/routes/../../src/Controller/ (which is being imported from \"/home/alumno/PhpstormProjects/symfony-contactos/config/routes/annotations.yaml\"). Make sure there is a loader supporting the \"annotation\" type. at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/config/Loader/FileLoader.php:172)\n[previous exception] [object] (ReflectionException(code: -1): Class \"\\ContactoController\" does not exist at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Loader/AnnotationDirectoryLoader.php:55)"} []
[2024-09-24T11:43:45.011708+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:43:45.012767+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:43:45.013757+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:43:45.014143+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:43:45.014907+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:43:45.020469+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:43:45.021461+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:44:19.134401+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "Class "\ContactoController" does not exist in /home/alumno/PhpstormProjects/symfony-contactos/config/routes/../../src/Controller/ (which is being imported from "/home/alumno/PhpstormProjects/symfony-contactos/config/routes/annotations.yaml"). Make sure there is a loader supporting the "annotation" type." at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/config/Loader/FileLoader.php line 172 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): Class \"\\ContactoController\" does not exist in /home/alumno/PhpstormProjects/symfony-contactos/config/routes/../../src/Controller/ (which is being imported from \"/home/alumno/PhpstormProjects/symfony-contactos/config/routes/annotations.yaml\"). Make sure there is a loader supporting the \"annotation\" type. at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/config/Loader/FileLoader.php:172)\n[previous exception] [object] (ReflectionException(code: -1): Class \"\\ContactoController\" does not exist at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Loader/AnnotationDirectoryLoader.php:55)"} []
[2024-09-24T11:44:19.217586+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:44:19.218536+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:44:19.219206+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:44:19.219463+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:44:19.220058+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:44:19.225503+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:44:19.226669+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:46:24.992156+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "Class "\ContactoController" does not exist in /home/alumno/PhpstormProjects/symfony-contactos/config/routes/../../src/Controller/ (which is being imported from "/home/alumno/PhpstormProjects/symfony-contactos/config/routes/annotations.yaml"). Make sure there is a loader supporting the "annotation" type." at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/config/Loader/FileLoader.php line 172 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): Class \"\\ContactoController\" does not exist in /home/alumno/PhpstormProjects/symfony-contactos/config/routes/../../src/Controller/ (which is being imported from \"/home/alumno/PhpstormProjects/symfony-contactos/config/routes/annotations.yaml\"). Make sure there is a loader supporting the \"annotation\" type. at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/config/Loader/FileLoader.php:172)\n[previous exception] [object] (ReflectionException(code: -1): Class \"\\ContactoController\" does not exist at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Loader/AnnotationDirectoryLoader.php:55)"} []
[2024-09-24T11:46:25.079575+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:46:25.080510+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:46:25.081125+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:46:25.081520+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:46:25.082026+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:46:25.087597+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:46:25.088247+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:47:36.755667+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "Class "\ContactoController" does not exist in /home/alumno/PhpstormProjects/symfony-contactos/config/routes/../../src/Controller/ (which is being imported from "/home/alumno/PhpstormProjects/symfony-contactos/config/routes/annotations.yaml"). Make sure there is a loader supporting the "annotation" type." at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/config/Loader/FileLoader.php line 172 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): Class \"\\ContactoController\" does not exist in /home/alumno/PhpstormProjects/symfony-contactos/config/routes/../../src/Controller/ (which is being imported from \"/home/alumno/PhpstormProjects/symfony-contactos/config/routes/annotations.yaml\"). Make sure there is a loader supporting the \"annotation\" type. at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/config/Loader/FileLoader.php:172)\n[previous exception] [object] (ReflectionException(code: -1): Class \"\\ContactoController\" does not exist at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Loader/AnnotationDirectoryLoader.php:55)"} []
[2024-09-24T11:47:36.841942+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:47:36.843212+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:47:36.844830+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:47:36.845211+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:47:36.846256+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:47:36.852201+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:47:36.853015+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:50:48.692779+02:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/error-handler/DebugClassLoader.php:331)"} []
[2024-09-24T11:53:13.233032+02:00] request.INFO: Matched route "ficha_contacto". {"route":"ficha_contacto","route_parameters":{"_route":"ficha_contacto","_controller":"App\\Controller\\ContactoController::ficha","codigo":"2"},"request_uri":"http://127.0.0.1:8080/contacto/2","method":"GET"} []
[2024-09-24T11:53:13.234370+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T11:53:13.234490+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:53:13.234604+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:53:13.239619+02:00] request.CRITICAL: Uncaught PHP Exception ReflectionException: "Class "App\Controller\ManagerRegistry" does not exist" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php line 171 {"exception":"[object] (ReflectionException(code: -1): Class \"App\\Controller\\ManagerRegistry\" does not exist at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php:171)"} []
[2024-09-24T11:53:13.270777+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:53:13.271765+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:53:13.272605+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:53:13.272898+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:53:13.273508+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:53:13.276209+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:53:13.276890+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:53:13.369904+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"57ead3"},"request_uri":"http://127.0.0.1:8080/_wdt/57ead3","method":"GET"} []
[2024-09-24T11:54:25.863916+02:00] request.INFO: Matched route "ficha_contacto". {"route":"ficha_contacto","route_parameters":{"_route":"ficha_contacto","_controller":"App\\Controller\\PageController::ficha","codigo":"2"},"request_uri":"http://127.0.0.1:8080/contacto/2","method":"GET"} []
[2024-09-24T11:54:25.865106+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T11:54:25.865222+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:54:25.865323+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:54:25.869510+02:00] request.CRITICAL: Uncaught PHP Exception ReflectionException: "Class "App\Controller\ManagerRegistry" does not exist" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php line 171 {"exception":"[object] (ReflectionException(code: -1): Class \"App\\Controller\\ManagerRegistry\" does not exist at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php:171)"} []
[2024-09-24T11:54:25.899771+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:25.900720+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:54:25.901585+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:54:25.901861+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:25.902458+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:54:25.905067+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:25.905629+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:54:25.993448+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"58f2a3"},"request_uri":"http://127.0.0.1:8080/_wdt/58f2a3","method":"GET"} []
[2024-09-24T11:54:31.527318+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8080/contacto"" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8080/contacto\" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/contacto/\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2024-09-24T11:54:31.575730+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:31.576731+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:54:31.577735+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:54:31.578189+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:31.578818+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:54:31.581456+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:31.582270+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:54:31.648616+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"cbe5db"},"request_uri":"http://127.0.0.1:8080/_wdt/cbe5db","method":"GET"} []
[2024-09-24T11:54:35.286433+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8080/contacto/"" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8080/contacto/\" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/contacto\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2024-09-24T11:54:35.337128+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:35.338074+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:54:35.338692+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:54:35.338960+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:35.339567+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:54:35.341981+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:54:35.342582+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:54:35.421616+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5b77d3"},"request_uri":"http://127.0.0.1:8080/_wdt/5b77d3","method":"GET"} []
[2024-09-24T11:55:46.168512+02:00] request.INFO: Matched route "inicio". {"route":"inicio","route_parameters":{"_route":"inicio","_controller":"App\\Controller\\PageController::inicio"},"request_uri":"http://127.0.0.1:8080/","method":"GET"} []
[2024-09-24T11:55:46.177139+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T11:55:46.177265+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:55:46.177367+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:55:46.275611+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:46.278420+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:55:46.280441+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:55:46.281929+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:46.282682+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:55:51.149114+02:00] request.INFO: Matched route "ficha_contacto". {"route":"ficha_contacto","route_parameters":{"_route":"ficha_contacto","_controller":"App\\Controller\\PageController::ficha","codigo":"2"},"request_uri":"http://127.0.0.1:8080/contacto/2","method":"GET"} []
[2024-09-24T11:55:51.150559+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T11:55:51.150758+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:55:51.150916+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:55:51.158610+02:00] request.CRITICAL: Uncaught PHP Exception ReflectionException: "Class "App\Controller\ManagerRegistry" does not exist" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php line 171 {"exception":"[object] (ReflectionException(code: -1): Class \"App\\Controller\\ManagerRegistry\" does not exist at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php:171)"} []
[2024-09-24T11:55:51.221431+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:51.222623+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:55:51.223412+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:55:51.223683+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:51.224349+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:55:51.226918+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:51.227863+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:55:51.337625+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"227abf"},"request_uri":"http://127.0.0.1:8080/_wdt/227abf","method":"GET"} []
[2024-09-24T11:55:54.465265+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8080/contacto"" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8080/contacto\" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/contacto/\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2024-09-24T11:55:54.513495+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:54.515362+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:55:54.518079+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:55:54.518556+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:54.519394+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:55:54.522052+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:54.522959+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:55:54.587189+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"380986"},"request_uri":"http://127.0.0.1:8080/_wdt/380986","method":"GET"} []
[2024-09-24T11:55:58.667354+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8080/contacto/"" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8080/contacto/\" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/contacto\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2024-09-24T11:55:58.716767+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:58.717707+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:55:58.718435+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:55:58.718766+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:58.719408+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:55:58.721826+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:55:58.722434+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:55:58.786359+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e2ae9c"},"request_uri":"http://127.0.0.1:8080/_wdt/e2ae9c","method":"GET"} []
[2024-09-24T11:57:03.142341+02:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/error-handler/DebugClassLoader.php:331)"} []
[2024-09-24T11:57:03.152408+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8080/contacto/2"" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8080/contacto/2\" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/contacto/2/\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2024-09-24T11:57:03.196570+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:03.197583+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:57:03.198435+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:57:03.198701+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:03.199383+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:57:03.201862+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:03.202499+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:57:03.285793+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"62bcff"},"request_uri":"http://127.0.0.1:8080/_wdt/62bcff","method":"GET"} []
[2024-09-24T11:57:06.979999+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8080/contacto/"" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8080/contacto/\" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/contacto\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2024-09-24T11:57:07.030765+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:07.032140+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:57:07.033399+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:57:07.033935+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:07.034942+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:57:07.037885+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:07.038832+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:57:07.107787+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"efc0d1"},"request_uri":"http://127.0.0.1:8080/_wdt/efc0d1","method":"GET"} []
[2024-09-24T11:57:48.268905+02:00] request.INFO: Matched route "ficha_contacto". {"route":"ficha_contacto","route_parameters":{"_route":"ficha_contacto","_controller":"App\\Controller\\PageController::ficha","codigo":"2"},"request_uri":"http://127.0.0.1:8080/contacto/2","method":"GET"} []
[2024-09-24T11:57:48.270126+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T11:57:48.270238+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:57:48.270342+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T11:57:48.276865+02:00] request.CRITICAL: Uncaught PHP Exception ReflectionException: "Class "App\Controller\ManagerRegistry" does not exist" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php line 171 {"exception":"[object] (ReflectionException(code: -1): Class \"App\\Controller\\ManagerRegistry\" does not exist at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php:171)"} []
[2024-09-24T11:57:48.308542+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:48.309560+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:57:48.310426+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:57:48.310702+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:48.311400+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:57:48.314010+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:48.314698+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:57:48.408794+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b43498"},"request_uri":"http://127.0.0.1:8080/_wdt/b43498","method":"GET"} []
[2024-09-24T11:57:50.753982+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8080/contacto/"" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8080/contacto/\" at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/contacto\". at /home/alumno/PhpstormProjects/symfony-contactos/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2024-09-24T11:57:50.803256+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:50.804345+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T11:57:50.805332+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T11:57:50.805631+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:50.806374+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:57:50.808943+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T11:57:50.809944+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T11:57:50.878584+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2144be"},"request_uri":"http://127.0.0.1:8080/_wdt/2144be","method":"GET"} []
[2024-09-24T12:05:14.171029+02:00] request.INFO: Matched route "ficha_contacto". {"route":"ficha_contacto","route_parameters":{"_route":"ficha_contacto","_controller":"App\\Controller\\PageController::ficha","codigo":"1"},"request_uri":"http://127.0.0.1:8080/contacto/1","method":"GET"} []
[2024-09-24T12:05:14.172250+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T12:05:14.172359+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T12:05:14.172459+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T12:05:14.180455+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T12:05:14.181401+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T12:05:14.182274+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T12:05:14.182541+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T12:05:14.183129+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T12:05:14.252678+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d31258"},"request_uri":"http://127.0.0.1:8080/_wdt/d31258","method":"GET"} []
[2024-09-24T12:05:35.683582+02:00] request.INFO: Matched route "ficha_contacto". {"route":"ficha_contacto","route_parameters":{"_route":"ficha_contacto","_controller":"App\\Controller\\PageController::ficha","codigo":"2"},"request_uri":"http://127.0.0.1:8080/contacto/2","method":"GET"} []
[2024-09-24T12:05:35.685749+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T12:05:35.685877+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T12:05:35.685979+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T12:05:35.697061+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T12:05:35.698357+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T12:05:35.699607+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T12:05:35.699982+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T12:05:35.700947+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T12:05:35.765234+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b4648d"},"request_uri":"http://127.0.0.1:8080/_wdt/b4648d","method":"GET"} []
[2024-09-24T12:07:29.344198+02:00] request.INFO: Matched route "ficha_contacto". {"route":"ficha_contacto","route_parameters":{"_route":"ficha_contacto","_controller":"App\\Controller\\PageController::ficha","codigo":"1"},"request_uri":"http://127.0.0.1:8080/contacto/1","method":"GET"} []
[2024-09-24T12:07:29.345353+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-09-24T12:07:29.345475+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T12:07:29.345582+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-09-24T12:07:29.356265+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T12:07:29.360281+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-09-24T12:07:29.361089+02:00] doctrine.INFO: Disconnecting [] []
[2024-09-24T12:07:29.361385+02:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"contactos","charset":"utf8mb4"}} []
[2024-09-24T12:07:29.362031+02:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'contactos' at /home/alumno/PhpstormProjects/symfony-contactos/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2024-09-24T12:07:29.446361+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"677f4c"},"request_uri":"http://127.0.0.1:8080/_wdt/677f4c","method":"GET"} []
